import 'dotenv/config';
import { google } from 'googleapis';
import express, { NextFunction, Request, Response } from 'express';
import Database from 'better-sqlite3';
import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken';
import helmet from 'helmet'; import cors from 'cors'; import rateLimit from 'express-rate-limit';
import { z } from 'zod'; import path from 'node:path'; import fs from 'node:fs';

const dbPath = process.env.DATABASE_PATH || './data/problem-solution.db'; fs.mkdirSync(path.dirname(dbPath), {recursive:true});
const db = new Database(dbPath); db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS problems (id TEXT PRIMARY KEY, age_range TEXT NOT NULL, description TEXT NOT NULL, frequency TEXT NOT NULL, current_solution TEXT, impacts TEXT NOT NULL, details TEXT, created_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'New', summary TEXT, category TEXT, tags TEXT, severity INTEGER, frequency_score INTEGER, solution_potential INTEGER, market_potential INTEGER, opportunity_score INTEGER, cluster_id TEXT);
CREATE TABLE IF NOT EXISTS clusters (id TEXT PRIMARY KEY, title TEXT NOT NULL, category TEXT, status TEXT NOT NULL DEFAULT 'New', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS solution_projects (id TEXT PRIMARY KEY, cluster_id TEXT NOT NULL, proposed_solution TEXT, mvp_features TEXT, validation_results TEXT, development_status TEXT NOT NULL DEFAULT 'Validating', feedback TEXT, launch_status TEXT NOT NULL DEFAULT 'Not launched', created_at TEXT NOT NULL);`);
const secret=process.env.JWT_SECRET || 'development-only-change-me'; const adminEmail=process.env.ADMIN_EMAIL || 'admin@example.com'; const adminPassword=process.env.ADMIN_PASSWORD || 'change-this-before-deploying';
const app=express(); app.use(helmet({contentSecurityPolicy:false})); app.use(cors()); app.use(express.json({limit:'30kb'})); app.use('/api/submit',rateLimit({windowMs:15*60*1000,max:8,standardHeaders:true,legacyHeaders:false}));
const sheetsId=process.env.GOOGLE_SHEETS_ID; const sheetsTab=process.env.GOOGLE_SHEETS_TAB||'Submissions'; const sheetsWebhook=process.env.GOOGLE_SHEETS_WEBHOOK_URL; const sheetsEmail=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL; const sheetsKey=process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,'\n'); const sheets=sheetsId&&sheetsEmail&&sheetsKey?google.sheets({version:'v4',auth:new google.auth.JWT({email:sheetsEmail,key:sheetsKey,scopes:['https://www.googleapis.com/auth/spreadsheets']})}):undefined;
const sheetHeaders=['Submitted at','Submission ID','Age range','Problem','Frequency','Current solution','Impacts','Additional details','Status','Summary','Category','Tags','Severity','Frequency score','Solution potential','Market potential','Opportunity score','Cluster ID'];
async function appendToGoogleSheet(row:(string|number)[]){if(sheetsWebhook){try{await fetch(sheetsWebhook,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sheet:sheetsTab,row,headers:sheetHeaders})});return}catch(error){console.error('Google Sheets webhook sync failed:',error instanceof Error?error.message:error);return}}if(!sheets||!sheetsId)return;try{const metadata=await sheets.spreadsheets.get({spreadsheetId:sheetsId,fields:'sheets.properties'});const exists=metadata.data.sheets?.some(sheet=>sheet.properties?.title===sheetsTab);if(!exists)await sheets.spreadsheets.batchUpdate({spreadsheetId:sheetsId,requestBody:{requests:[{addSheet:{properties:{title:sheetsTab}}}]}});const current=await sheets.spreadsheets.values.get({spreadsheetId:sheetsId,range:`${sheetsTab}!A1:R1`});if(!current.data.values?.length)await sheets.spreadsheets.values.append({spreadsheetId:sheetsId,range:`${sheetsTab}!A1`,valueInputOption:'RAW',requestBody:{values:[sheetHeaders]}});await sheets.spreadsheets.values.append({spreadsheetId:sheetsId,range:`${sheetsTab}!A:R`,valueInputOption:'RAW',insertDataOption:'INSERT_ROWS',requestBody:{values:[row]}})}catch(error){console.error('Google Sheets sync failed:',error instanceof Error?error.message:error)}}
const frequencies=['Every day','Several times a week','Once a week','Occasionally','Rarely'] as const;
const submission=z.object({ageRange:z.string().min(1).max(20),description:z.string().trim().min(25,'Please add a little more detail.').max(3000),frequency:z.enum(frequencies),currentSolution:z.string().max(1500).optional().default(''),impacts:z.array(z.string().max(60)).min(1).max(6),details:z.string().max(1000).optional().default('')});
const id=()=>crypto.randomUUID(); const auth=(req:Request,res:Response,next:NextFunction)=>{try{jwt.verify((req.headers.authorization||'').replace('Bearer ',''),secret);next()}catch{res.status(401).json({error:'Admin access required'})}};
function analyze(d:string,f:string){const x=d.toLowerCase(); const cats:[string,string[]][]=[['Transportation',['bus','train','traffic','commute']],['Education',['study','school','college','notes','course']],['Finance',['money','bill','bank','budget','expense']],['Health & Fitness',['health','workout','doctor','fitness']],['Work',['work','job','meeting','office']],['Home',['home','house','clean','repair']],['Shopping',['shop','buy','delivery','order']],['Technology',['app','software','phone','computer']]]; const found=cats.find(([,k])=>k.some(w=>x.includes(w))); const category=found?.[0]||'Productivity'; const tags=[...new Set((found?.[1]||['everyday','workflow']).filter(w=>x.includes(w)).concat(['real problem']))].slice(0,4); const fs=f==='Every day'?10:f==='Several times a week'?8:f==='Once a week'?6:f==='Occasionally'?4:2; const severity=Math.min(10,Math.max(3,Math.round(d.length/180)+4)); const potential=Math.min(10,Math.max(4,Math.round((severity+fs)/2))); const market=category==='Productivity'||category==='Technology'?8:6; const score=Math.round(severity*.3+fs*.2+potential*.3+market*.2); const summary=d.split(/[.!?]/)[0].slice(0,160); return {category,tags,severity,frequencyScore:fs,solutionPotential:potential,marketPotential:market,score,summary}; }
function matchingCluster(description:string,category:string){const rows=db.prepare('SELECT * FROM clusters WHERE category=?').all(category) as any[]; const words=new Set(description.toLowerCase().match(/[a-z]{4,}/g)||[]); for(const c of rows){const existing=db.prepare('SELECT description FROM problems WHERE cluster_id=? LIMIT 10').all(c.id) as any[]; if(existing.some(p=>[...words].filter(w=>p.description.toLowerCase().includes(w)).length>=2)) return c.id;} const cluster=id(); const title=category==='Productivity'?'Everyday workflow friction':category+' challenges'; db.prepare('INSERT INTO clusters (id,title,category,created_at) VALUES (?,?,?,?)').run(cluster,title,category,new Date().toISOString()); return cluster;}
app.post('/api/submit',(req,res)=>{const parsed=submission.safeParse(req.body); if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0].message}); const p=parsed.data; const a=analyze(p.description,p.frequency); const clusterId=matchingCluster(p.description,a.category); const pid=id(); const createdAt=new Date().toISOString(); db.prepare('INSERT INTO problems VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(pid,p.ageRange,p.description,p.frequency,p.currentSolution,JSON.stringify(p.impacts),p.details,createdAt,'New',a.summary,a.category,JSON.stringify(a.tags),a.severity,a.frequencyScore,a.solutionPotential,a.marketPotential,a.score,clusterId); void appendToGoogleSheet([createdAt,pid,p.ageRange,p.description,p.frequency,p.currentSolution,p.impacts.join(', '),p.details,'New',a.summary,a.category,a.tags.join(', '),a.severity,a.frequencyScore,a.solutionPotential,a.marketPotential,a.score,clusterId]); res.status(201).json({id:pid});});
app.post('/api/admin/login',(req,res)=>{const schema=z.object({email:z.string().email(),password:z.string().min(1)}).safeParse(req.body); if(!schema.success||schema.data.email!==adminEmail||!bcrypt.compareSync(schema.data.password,bcrypt.hashSync(adminPassword,10))) return res.status(401).json({error:'Invalid email or password'}); res.json({token:jwt.sign({role:'admin'},secret,{expiresIn:'8h'})});});
app.get('/api/admin/dashboard',auth,(_req,res)=>{const total=(db.prepare('SELECT count(*) n FROM problems').get() as any).n; const today=(db.prepare("SELECT count(*) n FROM problems WHERE created_at >= date('now')").get() as any).n; const week=(db.prepare("SELECT count(*) n FROM problems WHERE created_at >= date('now','-6 days')").get() as any).n; const categories=db.prepare('SELECT category label,count(*) value FROM problems GROUP BY category ORDER BY value DESC LIMIT 6').all(); const ages=db.prepare('SELECT age_range label,count(*) value FROM problems GROUP BY age_range').all(); const trends=db.prepare("SELECT substr(created_at,1,10) label,count(*) value FROM problems WHERE created_at >= date('now','-13 days') GROUP BY label").all(); res.json({total,today,week,categories,ages,trends});});
app.get('/api/admin/problems',auth,(req,res)=>{let rows=db.prepare('SELECT p.*,c.title cluster_title,(SELECT count(*) FROM problems p2 WHERE p2.cluster_id=p.cluster_id) similar_count FROM problems p LEFT JOIN clusters c ON c.id=p.cluster_id ORDER BY created_at DESC').all() as any[]; for(const key of ['category','frequency','status','ageRange'] as const){const val=req.query[key] as string; if(val) rows=rows.filter(x=>x[key==='ageRange'?'age_range':key]===val)} if(req.query.sort==='score')rows.sort((a,b)=>b.opportunity_score-a.opportunity_score); res.json(rows.map(r=>({...r,impacts:JSON.parse(r.impacts),tags:JSON.parse(r.tags||'[]')})));});
app.get('/api/admin/clusters',auth,(_req,res)=>res.json(db.prepare("SELECT c.*,count(p.id) submissions,round(avg(p.opportunity_score),1) opportunity_score FROM clusters c LEFT JOIN problems p ON p.cluster_id=c.id GROUP BY c.id ORDER BY submissions DESC").all()));
app.get('/api/admin/clusters/:id',auth,(req,res)=>{const c=db.prepare('SELECT * FROM clusters WHERE id=?').get(req.params.id); if(!c)return res.status(404).json({error:'Not found'}); const ps=db.prepare('SELECT * FROM problems WHERE cluster_id=? ORDER BY created_at DESC').all(req.params.id) as any[]; res.json({cluster:c,problems:ps.map(p=>({...p,impacts:JSON.parse(p.impacts)})),insight:'AI estimate: recurring reports suggest a viable area for user interviews before building.'});});
app.patch('/api/admin/clusters/:id',auth,(req,res)=>{const body=z.object({status:z.enum(['New','Analyzing','Clustered','Validating','Building','Testing','Launched'])}).safeParse(req.body);if(!body.success)return res.status(400).json({error:'Invalid status'});db.prepare('UPDATE clusters SET status=? WHERE id=?').run(body.data.status,req.params.id);res.json({ok:true})});
app.patch('/api/admin/problems/:id',auth,(req,res)=>{const body=z.object({status:z.enum(['New','Analyzing','Clustered','Validating','Building','Testing','Launched'])}).safeParse(req.body);if(!body.success)return res.status(400).json({error:'Invalid status'});db.prepare('UPDATE problems SET status=? WHERE id=?').run(body.data.status,req.params.id);res.json({ok:true})});
app.post('/api/admin/solution-projects',auth,(req,res)=>{const body=z.object({clusterId:z.string().uuid(),proposedSolution:z.string().max(3000).optional().default(''),mvpFeatures:z.array(z.string().max(200)).max(20).optional().default([]),validationResults:z.string().max(5000).optional().default('')}).safeParse(req.body);if(!body.success)return res.status(400).json({error:'Invalid project'});if(!db.prepare('SELECT id FROM clusters WHERE id=?').get(body.data.clusterId))return res.status(404).json({error:'Cluster not found'});const project=id();db.prepare('INSERT INTO solution_projects VALUES (?,?,?,?,?,?,?,?,?)').run(project,body.data.clusterId,body.data.proposedSolution,JSON.stringify(body.data.mvpFeatures),body.data.validationResults,'Validating','','Not launched',new Date().toISOString());res.status(201).json({id:project})});
app.use(express.static('dist')); app.use((_req,res)=>res.sendFile(path.resolve('dist/index.html')));
app.listen(Number(process.env.PORT)||3001,()=>console.log('Problem → Solution running'));
